name: Workflow Push
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm install and linter
        run: |
          npm install
          npm run lint
  test:
    depends-on: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Npm install and run test
        run: |
          npm install
          npm run test
